---
# tasks file for mysql-client
- name: Uninstall MariaDB
  yum:
    name: mariadb-libs
    state: absent

- name: Add MySQL repo
  yum:
    name: "{{ mysql_repo }}"
    state: present

- name: Install MySQL client
  yum:
    name: "{{ mysql_client_packages }}"
    state: present

