---
# tasks file for php
- name: Enable to install PHP
  command: "amazon-linux-extras enable php{{ php_version }}"
  changed_when: False

- name: Install PHP packages
  yum:
    name: "{{ php_packages }}"
    enablerepo: "{{ php_repo }}"
    state: present

- name: Delivery php.ini
  template:
    src: "php.ini.j2"
    dest: "/etc/php.ini"
  notify: restart_apache

